name: neighbornet_app
description: A simple NeighborNet Flutter app
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.20
  intl: ^0.18.1
  provider: ^6.0.5   # latest stable version
  file_picker: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
