# Generated by Django 5.2.8 on 2025-11-20 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='isFake',
            field=models.BooleanField(default=False),
        ),
    ]
