# Generated by Django 5.2.8 on 2025-11-20 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_report_isfake'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='highlighted',
        ),
        migrations.AddField(
            model_name='communitypost',
            name='isHighlighted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Verifed', 'Verifed'), ('Resolved', 'Resolved'), ('Rejected', 'Rejected')], default='Pending', max_length=100),
        ),
    ]
