# Generated by Django 5.2.8 on 2025-11-20 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_alert_highlighted_communitypost_ishighlighted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='localpoliceauthority',
            name='areaAssigned',
        ),
        migrations.RemoveField(
            model_name='localpoliceauthority',
            name='contactInfo',
        ),
    ]
