# Generated by Django 5.2.8 on 2025-11-21 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_report_latitude_report_longitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='isFake',
        ),
    ]
