# Generated by Django 5.2.8 on 2025-11-20 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_report_latitude_report_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='localpoliceauthority',
            name='areaAssigned',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
