# Generated by Django 5.2.8 on 2025-11-20 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_localpoliceauthority_areaassigned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='localpoliceauthority',
            name='areaAssigned',
        ),
    ]
