# Generated by Django 5.2.8 on 2025-11-22 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_remove_localpoliceauthority_areaassigned'),
        ('myapp', '0009_user_role'),
    ]

    operations = [
    ]
