# Generated by Django 5.2.8 on 2025-11-23 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_merge_20251122_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidence',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
